primary_region = "waw"
swap_size_mb = 512

[build]
dockerfile = "apps/site/Dockerfile"

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

[[vm]]
size = "shared-cpu-1x"
memory_mb = 256
