export const DATABASE_GROUP = "default";
export const DATABASE_REPLICA_URL = "file:replica.db";

export const FLY_SECRETS_NAMES = {
	DATABASE_AUTH_TOKEN: "DATABASE_AUTH_TOKEN",
	DATABASE_REPLICA_URL: "DATABASE_REPLICA_URL",
	DATABASE_SYNC_URL: "DATABASE_SYNC_URL",
	
	TURBO_TEAM: "TURBO_TEAM",
	TURBO_TOKEN: "TURBO_TOKEN",
} as const;
