export const metadata = {
  description: "Generated by create next app",
  title: "Create Next App",
};

const MainLayout = ({ children }: { children: React.ReactNode }) => (
  <html lang="en">
    <body>{children}</body>
  </html>
);

export default MainLayout;
