name: Install
description: Setup environment specific to this monorepo, including e.g. pnpm and node

runs:
  using: composite
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v2

    - name: Install node
      uses: actions/setup-node@v3
      with:
        node-version-file: "package.json"
        cache: "pnpm"

    - name: Install dependencies
      shell: bash
      run: pnpm i
