import type { Metadata } from "next";

import { Inter } from "next/font/google";

import "#src/app/main.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	description: "Generated by create next app",
	title: "Create Next App",
} satisfies Metadata;

export const fetchCache = "default-no-store";

// TODO: test disabling this + PPR after this https://github.com/caching-tools/next-shared-cache/issues/382
export const dynamic = "force-dynamic";

const RootLayout = ({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) => (
	<html lang="en">
		<body className={inter.className}>{children}</body>
	</html>
);

export default RootLayout;
