name: Setup
description: Setup node and pnpm

runs:
  using: composite
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@c3b53f6a16e57305370b4ae5a540c2077a1d50dd # pin@v2

    - name: Install node
      uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # pin@v3
      with:
        node-version-file: ".node-version"
        cache: "pnpm"

    - name: Install dependencies
      shell: bash
      run: pnpm i

    - name: Setup SvelteKit
      uses: pnpm svelte-kit sync
