name: 🔭 Create preview environment

on:
  pull_request:
    branches: [main]
    types: [opened]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}

env:
  ENVIRONMENT: preview-${{github.event.number}}

jobs:
  create-preview-environment:
    name: ✨ Create
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # pin@v4.1.1

      - name: Setup
        uses: ./.github/composite-actions/setup

      - name: Install flyctl
        uses: superfly/flyctl-actions/setup-flyctl@fc53c09e1bc3be6f54706524e3b82c4f462f77be # pin@1.5

      - name: Create preview environment
        run: pnpm  --filter="@pawelblaszczyk.dev/scripts" --fail-if-no-match environment:create --environment=$ENVIRONMENT
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
          TURBO_TEAM: ${{ vars.TURBO_TEAM }}
          TURSO_ORGANIZATION: ${{ vars.TURSO_ORGANIZATION }}
          TURSO_TOKEN: ${{ secrets.TURSO_TOKEN }}

      - name: Add info about creation
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # pin@v7.0.1
        env:
          PREVIEW_ENVIRONMENT_URL: https://pawelblaszczyk-dev-${{env.ENVIRONMENT}}-website.fly.dev
        with:
          script: |
            const { PREVIEW_ENVIRONMENT_URL } = process.env

            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `**Preview environment created ✨**

              Preview connected to this PR has been successfully created. Every commit to this PR should update it.

              Preview URL: ${PREVIEW_ENVIRONMENT_URL}`
            })
