name: Deploy development

on:
  push:
    branches:
      - dev

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}

jobs:
  deploy-app:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # pin@v3

      - name: Setup
        uses: ./.github/composite-actions/setup

      - name: Deploy app
        uses: ./.github/composite-actions/deploy-app
        with:
          api-token: ${{ secrets.FLY_DEVELOPMENT_API_TOKEN }}
          app-name: white-leaf-2342

  deploy-storybook:
    name: Deploy Storybook
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # pin@v3

      - name: Setup
        uses: ./.github/composite-actions/setup

      - name: Deploy app
        uses: ./.github/composite-actions/deploy-storybook
        with:
          api-token: ${{ secrets.SURGE_API_TOKEN }}
          app-domain: pawelblaszczyk-dev-storybook-development.surge.sh
