name: Update Lost Pixel baseline

on: workflow_dispatch

jobs:
  lost-pixel-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # pin@v3

      - name: Setup
        uses: ./.github/composite-actions/setup

      - name: Setup Playwright
        run: pnpm playwright install --with-deps

      - name: Build Storybook
        run: pnpm build:storybook

      - name: Run Lost Pixel update
        id: lost-pixel
        run: pnpm lost-pixel update
        env:
          LOST_PIXEL_UPDATE: true

      - name: Create PR
        uses: peter-evans/create-pull-request@38e0b6e68b4c852a5500a94740f0e535e0d7ba54 # pin@v4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          commit-message: Update Lost Pixel baseline
          delete-branch: true
          branch: "lost-pixel-update/${{ github.ref_name }}"
          title: "Lost Pixel update - ${{ github.ref_name }}"
          body: Automated baseline update PR

      - name: Upload screenshots
        uses: actions/upload-artifact@v3
        with:
          name: lost-pixel-artifacts
          path: .lostpixel
