name: Verify

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # pin@v3

      - name: Setup
        uses: ./.github/composite-actions/setup

      - name: Run build
        run: pnpm build

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # pin@v3

      - name: Setup
        uses: ./.github/composite-actions/setup

      - name: Run linting
        run: pnpm verify-lint

  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # pin@v3

      - name: Setup
        uses: ./.github/composite-actions/setup

      - name: Verify format
        run: pnpm verify-format

  typecheck:
    name: Typecheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # pin@v3

      - name: Setup
        uses: ./.github/composite-actions/setup

      - name: Run typechecking
        run: pnpm typecheck

  unit-test:
    name: Unit test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # pin@v3

      - name: Setup
        uses: ./.github/composite-actions/setup

      - name: Run unit tests
        run: pnpm test:unit

  e2e-test:
    name: E2E test
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # pin@v3

      - name: Setup
        uses: ./.github/composite-actions/setup

      - name: Setup Playwright
        run: pnpm playwright install --with-deps

      - name: Push schema into local database
        run: pnpm db:push

      - name: Run E2E tests
        run: pnpm test:e2e

  storybook-test:
    name: Storybook test
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # pin@v3

      - name: Setup
        uses: ./.github/composite-actions/setup

      - name: Setup Playwright
        run: pnpm playwright install --with-deps

      - name: Install additional dependencies for Storybook tests
        run: pnpm i -D concurrently http-server wait-on

      - name: Build Storybook
        run: pnpm build:storybook

      - name: Serve Storybook and run tests
        run: |
          pnpm concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
            "pnpm http-server storybook-static --port 6006 --silent" \
            "pnpm wait-on tcp:6006 && pnpm test:storybook --maxWorkers 1"

  visual-regression-test:
    name: Visual regression test
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # pin@v3

      - name: Setup
        uses: ./.github/composite-actions/setup

      - name: Setup Playwright
        run: pnpm playwright install --with-deps

      - name: Build Storybook
        run: pnpm build:storybook

      - name: Run Lost Pixel tests
        run: pnpm test:visual-regression
