name: Verify

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # pin@v3

      - name: Setup
        uses: ./.github/composite-actions/setup

      - name: Run build
        run: pnpm build

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # pin@v3

      - name: Setup
        uses: ./.github/composite-actions/setup

      - name: Run linting
        run: pnpm verify-lint

  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # pin@v3

      - name: Setup
        uses: ./.github/composite-actions/setup

      - name: Verify format
        run: pnpm verify-format

  typecheck:
    name: Typecheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # pin@v3

      - name: Setup
        uses: ./.github/composite-actions/setup

      - name: Run typechecking
        run: pnpm typecheck

  unit-test:
    name: Unit test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # pin@v3

      - name: Setup
        uses: ./.github/composite-actions/setup

      - name: Run unit tests
        run: pnpm test:unit

  e2e-test:
    name: E2E test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # pin@v3

      - name: Setup
        uses: ./.github/composite-actions/setup

      - name: Setup Playwright
        run: pnpm dlx playwright install --with-deps

      - name: Run E2E tests
        run: pnpm test:e2e
